### ISSUE TITLE
Investigate wether the CSI node driver needs a pre start socket removal

### ISSUE THREAD

**Issue by afritzler** [ironcore-dev/gardener-extension-provider-ironcore#544]
# Summary

As described here https://github.com/ironcore-dev/ironcore-csi-driver/issues/470 we might need a pre start removal of the CSI socket in the CSI node driver helm chart.

**Comment by sujeet01** [comment]
We currently have a preStop lifecycle hook in our `node-driver-registrar` container's YAML configuration [here](https://github.com/ironcore-dev/gardener-extension-provider-ironcore/blob/9fcb624271fe051a56d2450112e797d9e8a51284/charts/internal/shoot-system-components/charts/csi-driver-node/templates/daemonset.yaml#L91C1-L97C119) intended to remove the socket file. However, this hook fails because the image is distroless and does not include `/bin/sh` (refer to [this issue](https://github.com/kubernetes-csi/csi-driver-host-path/issues/175)). We need to remove this failing preStop hook.

Our CSI driver uses the [gocsi library](https://github.com/dell/gocsi), which manages socket cleanup during various conditions like graceful shutdown, abrupt stop, and startup errors (refer to [gocsi implementation](https://github.com/dell/gocsi/blob/554b1fc3ec9ae68ac65b095f8092c7cc1fb11181/gocsi.go#L105C1-L135C3)). We need to verify if it is working properly.

### Next steps:

- Remove the failing preStop lifecycle hook from the `node-driver-registrar` container.
- Verify the effectiveness of gocsi's socket cleanup mechanism.
- Consider adding additional socket cleanup steps in our CSI driver code before invoking `gocsi.Run`.

**Comment by afritzler** [comment]
Fixed via https://github.com/ironcore-dev/ironcore-csi-driver/pull/486
